name: Deploy payflex to WordPress.org

on:
  release:
    types: [published]   # click "Publish release" on GitHub to trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (fetch tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@v2.3.0
        with:
          generate-zip: 'false'   # set 'true' if you want a ZIP for the release asset
          dry-run: 'true'         # set 'false' to actually commit to SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: payflex-payment-gateway   # optional if repo name != WP.org slug